### ISSUE TITLE
还是一样 npm run dev运行不了

### ISSUE THREAD

**Issue by Yuri2** [walleeeee/daily-zhihu#16]
$ npm run dev

> zhihu@1.0.0 dev D:\Zhihu_vue\daily-zhihu
> node build/dev-server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'lodash/unionWith'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Zhihu_vue\daily-zhihu\node_modules\webpack-merge\l                                    ib\index.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                    node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! zhihu@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zhihu@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zhihu package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zhihu
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zhihu
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Zhihu_vue\daily-zhihu\npm-debug.log

**Comment by walleeeee** [comment]
cnpm install 再npm run dev
